---
- hosts: local
  vars_files:
    - vars/vault.yml
    - vars/default.yml
  roles:
    - role: git
      tags:
        - git

    - role: 1password
      tags:
        - 1password

    - role: docker
      tags:
        - docker

    - role: vscode
      tags:
        - vscode

    - role: firefox
      tags:
        - firefox

    - role: slack
      tags:
        - slack

    - role: zsh
      tags:
        - zsh

    - role: discord
      tags:
        - discord

    - role: spotify
      tags:
        - spotify

  pre_tasks:

    - name: user variable | set_fact
      set_fact:
        u: "{{lookup('env', 'USER')}}"

    - name: stop packagekitd | systemd
      become: true
      become_user: root
      systemd:
        name: packagekit
        state: stopped
        enabled: false

    - name: stop daily upgrade timer | systemd
      become: true
      become_user: root
      systemd:
        name: apt-daily-upgrade.timer
        state: stopped
        enabled: false

    - name: install wget | apt
      become: true
      become_user: root
      apt:
        name: wget
        state: present
        update_cache: true
    - name: install pexpect | pip
      pip:
        name: pexpect
