---
- hosts: local
  vars_files:
    - vars/default.yml
  roles:
    - role: docker
      tags:
        - docker

    - role: vscode
      tags:
        - vscode

    - role: firefox
      tags:
        - firefox

    - role: zsh
      tags:
        - zsh

    - role: 1password
      tags:
        - 1password

  pre_tasks:

    - name: user variable | set_fact
      set_fact:
        u: "{{lookup('env', 'USER')}}"

    - name: install wget | apt
      become: true
      become_user: root
      apt:
        name: wget
        state: present
        update_cache: true
