- name: link wallpaper | file
  file:
    src: "{{playbook_dir}}/resources/wallpaper.link.jpg"
    dest: "/home/{{u}}/.wallpaper.jpg"
    state: link
    force: true

- name: psutil
  become: true
  become_user: root
  apt:
    name: python3-psutil
    state: present

- name: set gnome wallpaper
  become_user: "{{u}}"
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///home/{{u}}/.wallpaper.jpg'"

- name: set gnome wallpaper dark
  become_user: "{{u}}"
  dconf:
    key: "/org/gnome/desktop/background/picture-uri-dark"
    value: "'file:///home/{{u}}/.wallpaper.jpg'"
