- name: install zsh | apt
  become: true
  become_user: root
  apt:
    name: zsh
    state: latest

- name: install jq | apt
  become: true
  become_user: root
  apt:
    name: jq
    state: latest

- name: set shell to zsh
  command: usermod --shell /bin/zsh {{u}}
  become: true
  become_user: root
  changed_when: false

- name: link .zshrc file | file
  file:
    src: "{{playbook_dir}}/roles/zsh/files/zshrc.link.zshrc"
    dest: "/home/{{u}}/.zshrc"
    state: link
    force: true

- name: link bash spinner
  file:
    src: "{{playbook_dir}}/roles/zsh/files/spinner.plugin.link.zsh"
    dest: "/home/{{u}}/.spinner"
    state: link
    force: true
