---

system_packages:
  [
    "1password",
    "discord",
    "slack-desktop"
  ]

vscode_extensions:
  - aaron-bond.better-comments
  - bmewburn.vscode-intelephense-client
  - bungcip.better-toml
  - ckolkman.vscode-postgres
  - dbaeumer.vscode-eslint
  - dsznajder.es7-react-js-snippets
  - GraphQL.vscode-graphql
  - IronGeek.vscode-env
  - ms-azuretools.vscode-docker
  - ms-python.python
  - ms-python.vscode-pylance
  - Prisma.prisma
  - rangav.vscode-thunder-client
  - redhat.ansible
  - redhat.vscode-yaml
  - Tyriar.sort-lines
  - wesbos.theme-cobalt2
  - wmaurer.change-case

git_config:
  - pull.rebase
  - fetch.prune
  - rebase.autostash
  - user.name

git_email_addresses:
  github: 6896115+alexogeny@users.noreply.github.com
  gitlab: 8857503-alexogeny@users.noreply.gitlab.com

zsh_plugins:
  - docker_icon
  - node_icon
  - package_icon
  - php_icon
  - python_icon
  - typescript_icon
  - yarn_icon
