---
vscode_extensions:
  - aaron-bond.better-comments
  - bmewburn.vscode-intelephense-client
  - bungcip.better-toml
  - ckolkman.vscode-postgres
  - dbaeumer.vscode-eslint
  - dsznajder.es7-react-js-snippets
  - GraphQL.vscode-graphql
  - IronGeek.vscode-env
  - junstyle.php-cs-fixer
  - mechatroner.rainbow-csv
  - ms-azuretools.vscode-docker
  - ms-python.python
  - ms-python.vscode-pylance
  - Prisma.prisma
  - rangav.vscode-thunder-client
  - redhat.ansible
  - redhat.vscode-yaml
  - streetsidesoftware.code-spell-checker
  - Tyriar.sort-lines
  - wesbos.theme-cobalt2
  - wmaurer.change-case

zsh_plugins:
  - docker_icon
  - node_icon
  - package_icon
  - php_icon
  - python_icon
  - typescript_icon
  - yarn_icon
