/**
 * User preferences file for Mozilla FireFox.
 *
 * Note that I don't watch any Netflix etc. so you'll need to reenable widevine
 * if you want that to work. YouTube should still work.
 *
 * This config will also break meeting software like google meet, teams, etc.
 * Strongly suggest having a standby browser if you want to use those. i.e.
 * keep a version of chromium alongised this that you only use for meets.
 */

user_pref('app.normandy.enabled', false)
user_pref('app.normandy.optoutstudies.enabled', false)
user_pref('beacon.enabled', false)
user_pref('browser.cache.disk.parent_directory', '/run/user/1000/firefox')
user_pref('browser.cache.memory.capacity', 512000)
user_pref('browser.download.panel.shown', true)
user_pref('browser.formfill.enable', false)
user_pref('browser.meta_refresh_when_inactive.disabled', true)
user_pref('browser.newtab.preload', false)
user_pref('browser.newtabpage.activity-stream.discoverystream.enabled', false)
user_pref('browser.newtabpage.activity-stream.feeds.discoverystreamfeed', false)
user_pref('browser.newtabpage.activity-stream.feeds.section.topstories', false)
user_pref('browser.newtabpage.activity-stream.feeds.telemetry', false)
user_pref('browser.newtabpage.activity-stream.section.highlights.includePocket', false)
user_pref('browser.newtabpage.activity-stream.showSponsored', false)
user_pref('browser.newtabpage.activity-stream.telemetry', false)
user_pref('browser.search.region', 'US')
user_pref('browser.send_pings.require_same_host', true)
user_pref('browser.send_pings', false)
user_pref('browser.sessionstore.interval', 600000)
user_pref('browser.sessionstore.max_tabs_undo', 3)
user_pref('browser.sessionstore.privacy_level', 1)
user_pref('browser.sessionstore.restore_on_demand', false)
user_pref('browser.sessionstore.restore_tabs_lazily', false)
user_pref('browser.urlbar.speculativeConnect.enabled', false)
user_pref('browser.urlbar.sponsoredTopSites', false)
user_pref('browser.urlbar.suggest.engines', false)
user_pref('browser.urlbar.suggest.history', false)
user_pref('browser.urlbar.suggest.searches', false)
user_pref('browser.urlbar.suggest.topsites', false)
user_pref('browser.zoom.full', false)
user_pref('device.sensors.enabled', false)
user_pref('devtools.remote.wifi.scan', false)
user_pref('dom.block_reload_from_resize_event_handler', true)
user_pref('dom.delay.block_external_protocol_in_iframes.enabled', true)
user_pref('dom.gamepad.enabled', false)
user_pref('dom.gamepad.extensions.enabled', false)
user_pref('dom.security.https_only_mode_ever_enabled', true)
user_pref('dom.security.https_only_mode.upgrade_local', true)
user_pref('dom.security.https_only_mode', true)
user_pref('dom.vibrator.enabled', false)
user_pref('dom.vr.enabled', false)
user_pref('dom.vr.oculus.enabled', false)
user_pref('dom.webaudio.enabled', false)
user_pref('extensions.blocklist.enabled', false)
user_pref('extensions.pocket.enabled', false)
user_pref('fission.autostart', true)
user_pref('geo.enabled', false)
user_pref('geo.provider.ms-windows-location', false)
user_pref('gfx.canvas.remote', false)
user_pref('media.eme.enabled', false)
user_pref('media.gmp-widevinecdm.enabled', false)
user_pref('media.gmp-widevinecdm.enabled', false)
user_pref('media.navigator.enabled', false)
user_pref('media.peerconnection.enabled', false)
user_pref('media.peerconnection.identity.enabled', false)
user_pref('media.peerconnection.simulcast', false)
user_pref('media.peerconnection.turn.disable', true)
user_pref('media.peerconnection.use_document_iceservers', false)
user_pref('media.peerconnection.video.enabled', false)
user_pref('media.videocontrols.picture-in-picture.video-toggle.enabled', false)
user_pref('media.webspeech.synth.enabled', false)
user_pref('messaging-system.rsexperimentloader.enabled', false)
user_pref('network.captive-portal-service.enabled', false)
user_pref('network.connectivity-service.enabled', false)
user_pref('network.dns.disableIPv6', true)
user_pref('network.dns.disablePrefetch', true)
user_pref('network.dns.offline-localhost', false)
user_pref('network.http.referer.sendRefererHeader', 1)
user_pref('network.http.referer.trimmingPolicy', 1)
user_pref('network.http.referer.XOriginPolicy', 1)
user_pref('network.http.speculative-parallel-limit', 0)
user_pref('network.IDN_show_punycode', true)
user_pref('network.predictor.enabled', false)
user_pref('network.prefetch-next', false)
user_pref('network.stricttransportsecurity.preloadlist', false)
user_pref('places.history.enabled', false)
user_pref('privacy.donottrackheader.enabled', true)
user_pref('privacy.resistFingerprinting', true)
user_pref('toolkit.telemetry.enabled', false)
user_pref('toolkit.telemetry.firstShutdownPing.enabled', false)
user_pref('toolkit.telemetry.newProfilePing.enabled', false)
user_pref('toolkit.telemetry.pioneer-new-studies-available', false)
user_pref('toolkit.telemetry.shutdownPingSender.enabled', false)
user_pref('toolkit.telemetry.unified', false)
user_pref('trailhead.firstrun.didSeeAboutWelcome', true)
