- name: install php | apt
  become: true
  become_user: root
  apt:
    name: php
    state: latest

- name: ensure apache2 is stopped | systemd
  become: true
  become_user: root
  systemd:
    name: apache2
    state: stopped
    enabled: false
