- name: install php | apt
  become: true
  become_user: root
  apt:
    name: php
    state: latest

- name: ensure apache2 is stopped | systemd
  become: true
  become_user: root
  systemd:
    name: apache2
    state: stopped
    enabled: false

- name: has composer
  stat:
    path: /usr/local/bin/composer
  register: has_composer

- name: download composer
  become: true
  become_user: root
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer
  when: not has_composer.stat.exists

- name: install composer
  become: true
  shell: cat /tmp/composer-installer | php -- --install-dir=/usr/local/bin
  args:
    creates: /usr/local/bin/composer
  when: not has_composer.stat.exists

- name: rename composer.phar
  become: true
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
  args:
    creates: /usr/local/bin/composer
  when: not has_composer.stat.exists

- name: make composer executable
  become: true
  file:
    path: /usr/local/bin/composer
    mode: a+x
    state: file
  when: not has_composer.stat.exists

- name: has php cs fixer
  stat:
    path: /home/{{u}}/.config/composer/vendor/bin/php-cs-fixer
  register: has_php_cs_fixer

- name: install php cs fixer
  community.general.composer:
    command: require
    global_command: yes
    arguments: friendsofphp/php-cs-fixer
  when: not has_php_cs_fixer.stat.exists

- name: link php cs fixer config
  file:
    src: "{{playbook_dir}}/roles/php/files/php-cs-fixer.link.php"
    dest: /home/{{u}}/.php-cs-fixer.php
    state: link
    force: true
