- name: is 1password signing key present | stat
  stat:
    path: /etc/apt/trusted.gpg.d/1password.gpg
  register: has_1password_signing_key

- name: install 1password signing key | shell
  become: true
  become_user: root
  shell: |
    wget -qO- https://downloads.1password.com/linux/keys/1password.asc |
    gpg --dearmor > /tmp/1password.gpg
    install -o root -g root -m 644 /tmp/1password.gpg /etc/apt/trusted.gpg.d/
    rm -f /tmp/1password.gpg
  when: not has_1password_signing_key.stat.exists

- name: is 1password repo present
  stat:
    path: /etc/apt/sources.list.d/1password.list
  register: has_1password_repo

- name: 1password repo | apt
  become: true
  become_user: root
  apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/1password.gpg] https://downloads.1password.com/linux/debian/amd64 stable main
    state: present
    filename: 1password
  when: not has_1password_repo.stat.exists

- name: install 1password | apt
  become: true
  become_user: root
  apt:
    name:
      - 1password
      - 1password-cli
    state: latest

- name: has 1password account | shell
  command: op account list
  register: has_1password_account
  changed_when: False

- name: add 1password account | one_password
  one_password:
    login_details:
      password: "{{one_password.password}}"
      key: "{{one_password.secret_key}}"
      email: "{{one_password.email}}"
    command: login
  when: has_1password_account.stdout == ""

- name: ssh folder
  file:
    path: /home/{{u}}/.ssh
    state: directory

- name: ssh file
  copy:
    dest: /home/{{u}}/.ssh/config
    content: |
      Host *
        IdentityAgent /home/{{u}}/.1password/agent.sock
